// Code generated by tools/gends; DO NOT EDIT.
package datasource

import (
	"context"

	"github.com/euc-oss/terraform-provider-uem/internal/providerdata"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &macApplicationDataSource{}
var _ datasource.DataSourceWithConfigure = &macApplicationDataSource{}

// macApplicationSearchIface is the seam the hand-written companion (newSearch) implements.
type macApplicationSearchIface interface {
	List(ctx context.Context, filters macApplicationFilters) ([]MacApplicationSummary, error)
}

type macApplicationDataSource struct{ search macApplicationSearchIface }

func NewMacApplicationDataSource() datasource.DataSource { return &macApplicationDataSource{} }

type macApplicationFilters struct {
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
}

type MacApplicationDataSourceModel struct {
	OrganizationGroupUuid types.String            `tfsdk:"organization_group_uuid"`
	Items                 []MacApplicationSummary `tfsdk:"mac_applications"`
}

type MacApplicationSummary struct {
	BundleId              types.String `tfsdk:"bundle_id"`
	Id                    types.Int64  `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
	Type                  types.String `tfsdk:"type"`
	Uuid                  types.String `tfsdk:"uuid"`
}

func (d *macApplicationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mac_applications"
}

func (d *macApplicationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"organization_group_uuid": schema.StringAttribute{Optional: true},
		"mac_applications": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
			"bundle_id":               schema.StringAttribute{Computed: true},
			"id":                      schema.Int64Attribute{Computed: true},
			"name":                    schema.StringAttribute{Computed: true},
			"organization_group_uuid": schema.StringAttribute{Computed: true},
			"type":                    schema.StringAttribute{Computed: true},
			"uuid":                    schema.StringAttribute{Computed: true},
		}}},
	}}
}

func (d *macApplicationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	pd, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Configure Type", "expected *providerdata.ProviderData")
		return
	}
	if pd == nil || pd.Client == nil {
		resp.Diagnostics.AddError("Provider Not Fully Configured", "provider data or client is nil")
		return
	}
	d.search = newSearch(pd)
}

func (d *macApplicationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data MacApplicationDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	filters := macApplicationFilters{OrganizationGroupUuid: data.OrganizationGroupUuid}
	items, err := d.search.List(ctx, filters)
	if err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	data.Items = items
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
