// Code generated by tools/gends; DO NOT EDIT.
package scripts

import (
	"context"

	"github.com/euc-oss/terraform-provider-uem/internal/providerdata"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &scriptDataSource{}
var _ datasource.DataSourceWithConfigure = &scriptDataSource{}

// scriptSearchIface is the seam the hand-written companion (newSearch) implements.
type scriptSearchIface interface {
	List(ctx context.Context, filters scriptFilters) ([]ScriptSummary, error)
}

type scriptDataSource struct{ search scriptSearchIface }

func NewScriptDataSource() datasource.DataSource { return &scriptDataSource{} }

type scriptFilters struct {
	Name                  types.String `tfsdk:"name"`
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
}

type ScriptDataSourceModel struct {
	Name                  types.String    `tfsdk:"name"`
	OrganizationGroupUuid types.String    `tfsdk:"organization_group_uuid"`
	Items                 []ScriptSummary `tfsdk:"scripts"`
}

type ScriptSummary struct {
	Name                  types.String `tfsdk:"name"`
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
	Platform              types.String `tfsdk:"platform"`
	ScriptType            types.String `tfsdk:"script_type"`
	ScriptUuid            types.String `tfsdk:"script_uuid"`
	Version               types.String `tfsdk:"version"`
}

func (d *scriptDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_scripts"
}

func (d *scriptDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"name":                    schema.StringAttribute{Optional: true},
		"organization_group_uuid": schema.StringAttribute{Required: true},
		"scripts": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
			"name":                    schema.StringAttribute{Computed: true},
			"organization_group_uuid": schema.StringAttribute{Computed: true},
			"platform":                schema.StringAttribute{Computed: true},
			"script_type":             schema.StringAttribute{Computed: true},
			"script_uuid":             schema.StringAttribute{Computed: true},
			"version":                 schema.StringAttribute{Computed: true},
		}}},
	}}
}

func (d *scriptDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	pd, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Configure Type", "expected *providerdata.ProviderData")
		return
	}
	if pd == nil || pd.Client == nil {
		resp.Diagnostics.AddError("Provider Not Fully Configured", "provider data or client is nil")
		return
	}
	d.search = newSearch(pd)
}

func (d *scriptDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ScriptDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	filters := scriptFilters{Name: data.Name, OrganizationGroupUuid: data.OrganizationGroupUuid}
	items, err := d.search.List(ctx, filters)
	if err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	data.Items = items
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
