// Code generated by tools/gends; DO NOT EDIT.
package sensors

import (
	"context"

	"github.com/euc-oss/terraform-provider-uem/internal/providerdata"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ datasource.DataSource = &sensorDataSource{}
var _ datasource.DataSourceWithConfigure = &sensorDataSource{}

// sensorSearchIface is the seam the hand-written companion (newSearch) implements.
type sensorSearchIface interface {
	List(ctx context.Context, filters sensorFilters) ([]SensorSummary, error)
}

type sensorDataSource struct{ search sensorSearchIface }

func NewSensorDataSource() datasource.DataSource { return &sensorDataSource{} }

type sensorFilters struct {
	Name                  types.String `tfsdk:"name"`
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
}

type SensorDataSourceModel struct {
	Name                  types.String    `tfsdk:"name"`
	OrganizationGroupUuid types.String    `tfsdk:"organization_group_uuid"`
	Items                 []SensorSummary `tfsdk:"sensors"`
}

type SensorSummary struct {
	Id                    types.Int64  `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	OrganizationGroupUuid types.String `tfsdk:"organization_group_uuid"`
	Platform              types.String `tfsdk:"platform"`
	Uuid                  types.String `tfsdk:"uuid"`
}

func (d *sensorDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_sensors"
}

func (d *sensorDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{Attributes: map[string]schema.Attribute{
		"name":                    schema.StringAttribute{Optional: true},
		"organization_group_uuid": schema.StringAttribute{Required: true},
		"sensors": schema.ListNestedAttribute{Computed: true, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
			"id":                      schema.Int64Attribute{Computed: true},
			"name":                    schema.StringAttribute{Computed: true},
			"organization_group_uuid": schema.StringAttribute{Computed: true},
			"platform":                schema.StringAttribute{Computed: true},
			"uuid":                    schema.StringAttribute{Computed: true},
		}}},
	}}
}

func (d *sensorDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	pd, ok := req.ProviderData.(*providerdata.ProviderData)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Configure Type", "expected *providerdata.ProviderData")
		return
	}
	if pd == nil || pd.Client == nil {
		resp.Diagnostics.AddError("Provider Not Fully Configured", "provider data or client is nil")
		return
	}
	d.search = newSearch(pd)
}

func (d *sensorDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data SensorDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	filters := sensorFilters{Name: data.Name, OrganizationGroupUuid: data.OrganizationGroupUuid}
	items, err := d.search.List(ctx, filters)
	if err != nil {
		resp.Diagnostics.AddError("Read failed", err.Error())
		return
	}
	data.Items = items
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
